patterns:
	python3 gen_patterns.py data/ccobra_control.csv data/ccobra_1s.csv
	python3 gen_patterns.py data/ccobra_control.csv data/ccobra_10s.csv
	python3 gen_patterns.py data/ccobra_1s.csv data/ccobra_10s.csv

plot_patterns:
	python3 plot_fig1.py ccobra_control ccobra_1s
	python3 plot_fig1.py ccobra_control ccobra_10s
	python3 plot_fig1.py ccobra_1s ccobra_10s
